# Wrangler configuration for Cloudflare Pages
name = "wyldeflowersguide"
compatibility_date = "2025-04-05"

# Pages configuration
pages_build_output_dir = "build"

# Build configuration
[build]
command = "npm run build"

# Environment variables
[vars]
NODE_VERSION = "20"

# Production environment
[env.production]
workers_dev = false
routes = [
  { pattern = "wyldeflowersguide.pages.dev/*", zone_name = "wyldeflowersguide.pages.dev" }
]

# Staging environment
[env.staging]
name = "wyldeflowersguide-staging"
workers_dev = true
