# Wrangler configuration for Cloudflare Pages
name = "wyldeflowersguide"
compatibility_date = "2025-04-05"

# Build configuration for SvelteKit with static adapter
[build]
command = "npm run build"
output_directory = "build"

# Environment variables
[vars]
NODE_VERSION = "18"

# Production environment
[env.production]
workers_dev = false
routes = [
  { pattern = "wyldeflowersguide.pages.dev/*", zone_name = "wyldeflowersguide.pages.dev" }
]

# Staging environment
[env.staging]
name = "wyldeflowersguide-staging"
workers_dev = true
